module IN
	DESCRIPTION = 4
	DOC_NUMBER = 5
	DOC_DATE = 6
	PURCHASE_AMOUNT = 8
	BSSI_FACILITY = 37
	VENDOR = 164
	DOC_TYPE = 63
	COMPANY_REQUEST_ORG = 37
	JOURNAL_ACCOUNT_CODE = 60
	JOURNAL_AMOUNT = 61
	COMPANY_ALLOCATION = 68
	DIVISION_ALLOCATION = 69
	DEPARTMENT_ALLOCATION = 70
	PO_NUMBER = 1
	REMIT_TO_ID = 165
	DELIVERY = 15
	CARRIER_HANDLER = 16
end

module OUT
	PO_NUMBER = 0
	DESCRIPTION = 1
	DOC_NUMBER = 2
	DOC_DATE = 3
	PURCHASE_AMOUNT = 4
	DELIVERY = 5
	CARRIER_HANDLER = 6
	BSSI_FACILITY = 7
	COMPANY_REQUEST_ORG = 8
	JOURNAL_ACCOUNT_CODE = 9
	JOURNAL_AMOUNT = 10
	DOC_TYPE = 11
	COMPANY_ALLOCATION = 12
	DIVISION_ALLOCATION = 13
	DEPARTMENT_ALLOCATION = 14
	REMIT_TO_ID = 15
	VENDOR = 16
	BATCHID = 17
	SHA1KEY = 18
	VOUCHER=19
	BSSI_INTERCOMPANY=20
	BSSI_MAX=21
	ACCOUNT = 22
	AGG_ACCOUNT=23
	AGG_SUM=24
	SOURCE_FILE=25
	TAG=26
end
